import os

Import('global_env')

env = global_env.Clone()
# allowed colored terminal
if 'TERM' in os.environ:
    env['ENV']['TERM'] = os.environ['TERM']


outdir = GetOption('outdir')
curr_path = os.path.join(Dir('#').abspath, 'src/lib')
sources = env.get_files(curr_path, ['cpp', 'c'])
objects = map(lambda x: env.Object(x, variant_dir=outdir, duplicate=False), sources)

static_lib = env.StaticLibrary('rocketgen_static', objects)
Return('static_lib')
