sudo: false
language: generic

addons:
  apt:
    sources:
      - llvm-toolchain-precise
      - ubuntu-toolchain-r-test
    packages:
      - scons
      - g++-5
      - gcc-5
      - clang-3.8

compiler:
  - clang
  - gcc

script:
  - if [ "$CXX" = "clang++" ]; then scons --clang --travis; fi
  - if [ "$CXX" = "g++" ]; then scons --travis; fi
